esphome:
  name: pilight-dev

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4MbJUfxFAPRqGmVBWru5BpY3NERA5RoCjeEydJZ4TOE="

ota:
  password: "a596b158949ebc6be1b43302606c356f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Pilight-Dev Fallback Hotspot"
    password: "sDcuGB2e5xiV"

output:
  - platform: gpio
    pin:
      number: 32 #Onboard LED PicoW
      mode: output
    id: LED

interval:
  - interval: 3000ms
    then:
      - output.turn_on: LED
      - delay: 1500ms
      - output.turn_off: LED

switch:
  - platform: gpio
    pin: 
      number: 22
    name: "PiLight-Dev : Red"
  - platform: gpio
    pin: 
      number: 21
    name: "PiLight-Dev : Green"
  - platform: gpio
    pin: 
      number: 20
    name: "PiLight-Dev : Blue"