esphome:
  name: pilight-dev

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4MbJUfxFAPRqGmVBWru5BpY3NERA5RoCjeEydJZ4TOE="

ota:
  password: "a596b158949ebc6be1b43302606c356f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: gpio
    pin:
      number: 32 #Onboard LED PicoW
      mode: output
    id: LED
  - platform: rp2040_pwm
    pin: 22
    frequency: 1000 Hz
    id: pwm_red
  - platform: rp2040_pwm
    pin: 21
    frequency: 1000 Hz
    id: pwm_green
  - platform: rp2040_pwm
    pin: 20
    frequency: 1000 Hz
    id: pwm_blue

interval:
  - interval: 3000ms
    then:
      - output.turn_on: LED
      - delay: 1500ms
      - output.turn_off: LED

light:
  - platform: rgb
    name: "PiLight-Dev RGB"
    red: pwm_red
    green: pwm_green
    blue: pwm_blue